version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:random-key
    command: php artisan serve --host=0.0.0.0 --port=8000